SET PATH=C:\Keil\ARM\BIN40\;C:\Program Files\ARM\bin\win_32-pentium;C:\Program Files\ARM\RVD\Core\1.8\734\win_32-pentium\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\TortoiseGit\bin;C:\Program Files\ARM\RVCT\Programs\2.2\349\win_32-pentium;C:\Program Files\ARM\Utilities\FLEXlm\9.2\release\win_32-pentium;C:\Documents and Settings\Administrator\Local Settings\Application Data\Kingsoft\WPS Office\8.1.0.3526\office6;E:\开发工具软件\编程软件\VC\VC6EN\Tools\WinNT;E:\开发工具软件\编程软件\VC\VC6EN\MSDev98\Bin;E:\开发工具软件\编程软件\VC\VC6EN\Tools;E:\开发工具软件\编程软件\VC\VC98\bin;C:\Program Files\ATMEL Corporation\AT91-ISP v1.12\SAM-BA v2.8;C:\Program Files\ATMEL Corporation\AT91-ISP v1.12\Library\
SET ARMCC41INC=C:\Keil\ARM\RV31\INC
SET ARMCC41LIB=C:\Keil\ARM\RV31\LIB
SET CPU_TYPE=STM32F103ZE
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=rtthread-stm32
SET CPU_CLOCK=0x00000000
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\local.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\alarm.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\gprs.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\application.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\startup.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via ".\obj\board.__i"
