Import('RTT_ROOT')
from building import *

src	= Glob('*.c')
CPPDEFINES = []
if GetDepend('RT_USING_MINILIBC'):
   CPPPATH = [RTT_ROOT + '/components/libc/minilibc']
else:
   CPPPATH = []

group = DefineGroup('minilibc', src, 
	depend = ['RT_USING_MINILIBC'], 
	CPPPATH = CPPPATH,
	CPPDEFINES = CPPDEFINES
	)

Return('group')
